# Form implementation generated from reading ui file 'Homewindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(180, 140))
        MainWindow.setMaximumSize(QtCore.QSize(16777, 16777))
        MainWindow.setStyleSheet("QMainWindow {\n"
"   \n"
"    background-color: #F0FDF4;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777, 16777))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 140, 690, 354))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.btnedit = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnedit.sizePolicy().hasHeightForWidth())
        self.btnedit.setSizePolicy(sizePolicy)
        self.btnedit.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        self.btnedit.setFont(font)
        self.btnedit.setStyleSheet("QPushButton {\n"
"    background-color: #62a37c;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"    padding: 20px;\n"
"    border: none;\n"
"\n"
"  }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #43e97b,\n"
"        stop: 1 #38f9d7\n"
"    );\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f4037;\n"
"}")
        self.btnedit.setObjectName("btnedit")
        self.gridLayout.addWidget(self.btnedit, 0, 2, 1, 1)
        self.btnview = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnview.sizePolicy().hasHeightForWidth())
        self.btnview.setSizePolicy(sizePolicy)
        self.btnview.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        self.btnview.setFont(font)
        self.btnview.setStyleSheet("QPushButton {\n"
"    background-color: #62a37c;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"    padding: 20px;\n"
"    border: none;\n"
"\n"
"  }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #43e97b,\n"
"        stop: 1 #38f9d7\n"
"    );\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f4037;\n"
"}")
        self.btnview.setObjectName("btnview")
        self.gridLayout.addWidget(self.btnview, 1, 1, 1, 1)
        self.btndelete = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btndelete.sizePolicy().hasHeightForWidth())
        self.btndelete.setSizePolicy(sizePolicy)
        self.btndelete.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        self.btndelete.setFont(font)
        self.btndelete.setStyleSheet("QPushButton {\n"
"    background-color: #62a37c;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"    padding: 20px;\n"
"    border: none;\n"
"\n"
"  }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #43e97b,\n"
"        stop: 1 #38f9d7\n"
"    );\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f4037;\n"
"}")
        self.btndelete.setObjectName("btndelete")
        self.gridLayout.addWidget(self.btndelete, 1, 0, 1, 1)
        self.btnothers = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnothers.sizePolicy().hasHeightForWidth())
        self.btnothers.setSizePolicy(sizePolicy)
        self.btnothers.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        self.btnothers.setFont(font)
        self.btnothers.setStyleSheet("QPushButton {\n"
"    background-color: #62a37c;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"    padding: 20px;\n"
"    border: none;\n"
"\n"
"  }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #43e97b,\n"
"        stop: 1 #38f9d7\n"
"    );\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f4037;\n"
"}")
        self.btnothers.setObjectName("btnothers")
        self.gridLayout.addWidget(self.btnothers, 1, 2, 1, 1)
        self.btnsearch = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnsearch.sizePolicy().hasHeightForWidth())
        self.btnsearch.setSizePolicy(sizePolicy)
        self.btnsearch.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        self.btnsearch.setFont(font)
        self.btnsearch.setStyleSheet("QPushButton {\n"
"    background-color: #62a37c;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"    padding: 20px;\n"
"    border: none;\n"
"\n"
"  }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #43e97b,\n"
"        stop: 1 #38f9d7\n"
"    );\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f4037;\n"
"}")
        self.btnsearch.setObjectName("btnsearch")
        self.gridLayout.addWidget(self.btnsearch, 0, 1, 1, 1)
        self.btnadd = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnadd.sizePolicy().hasHeightForWidth())
        self.btnadd.setSizePolicy(sizePolicy)
        self.btnadd.setMinimumSize(QtCore.QSize(150, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        self.btnadd.setFont(font)
        self.btnadd.setStyleSheet("QPushButton {\n"
"    background-color: #62a37c;\n"
"    color: black;\n"
"    border-radius: 20px;\n"
"    padding: 20px;\n"
"    border: none;\n"
"\n"
"  }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #43e97b,\n"
"        stop: 1 #38f9d7\n"
"    );\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f4037;\n"
"}")
        self.btnadd.setObjectName("btnadd")
        self.gridLayout.addWidget(self.btnadd, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 801, 81))
        self.widget_2.setStyleSheet("background-color: #14532D;")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(56, 6, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(68, 176, 61);\n"
"\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=self.widget_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.widget.setStyleSheet("QWidget{\n"
"    border-image: url(D:/first/LibManage/img/bookIcon.jpg);\n"
"}")
        self.widget.setObjectName("widget")
        self.btnprofile = QtWidgets.QToolButton(parent=self.widget_2)
        self.btnprofile.setGeometry(QtCore.QRect(750, 10, 27, 27))
        self.btnprofile.setStyleSheet("QToolButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.btnprofile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/userIcon.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnprofile.setIcon(icon)
        self.btnprofile.setIconSize(QtCore.QSize(24, 24))
        self.btnprofile.setObjectName("btnprofile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnedit.setText(_translate("MainWindow", "Edit "))
        self.btnview.setText(_translate("MainWindow", "View"))
        self.btndelete.setText(_translate("MainWindow", "Delete "))
        self.btnothers.setText(_translate("MainWindow", "others"))
        self.btnsearch.setText(_translate("MainWindow", "Search "))
        self.btnadd.setText(_translate("MainWindow", "Add "))
        self.label.setText(_translate("MainWindow", "Library Management System"))
