# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 442)
        MainWindow.setMaximumSize(QtCore.QSize(16777, 16777))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    border-image: url(D:/first/LibManage/img/background.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777200, 16777200))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.widgetMain = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetMain.setGeometry(QtCore.QRect(450, 60, 261, 281))
        self.widgetMain.setAutoFillBackground(False)
        self.widgetMain.setStyleSheet("#widgetMain {\n"
"    background-color: #91c2a3;\n"
"}")
        self.widgetMain.setObjectName("widgetMain")
        self.lblpwd = QtWidgets.QLabel(parent=self.widgetMain)
        self.lblpwd.setGeometry(QtCore.QRect(10, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        self.lblpwd.setFont(font)
        self.lblpwd.setObjectName("lblpwd")
        self.lbluser = QtWidgets.QLabel(parent=self.widgetMain)
        self.lbluser.setGeometry(QtCore.QRect(10, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        self.lbluser.setFont(font)
        self.lbluser.setStyleSheet("")
        self.lbluser.setObjectName("lbluser")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widgetMain)
        self.lineEdit.setGeometry(QtCore.QRect(110, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widgetMain)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.btnlogin = QtWidgets.QPushButton(parent=self.widgetMain)
        self.btnlogin.setGeometry(QtCore.QRect(180, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.btnlogin.setFont(font)
        self.btnlogin.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #22C55E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #91e3af;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b4c2b9;\n"
"}")
        self.btnlogin.setObjectName("btnlogin")
        self.pushButton = QtWidgets.QPushButton(parent=self.widgetMain)
        self.pushButton.setGeometry(QtCore.QRect(180, 250, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #22C55E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #91e3af;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #b4c2b9;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.widgetIcon = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetIcon.setGeometry(QtCore.QRect(160, 40, 51, 51))
        self.widgetIcon.setStyleSheet("QWidget{\n"
"    border-image: url(D:/first/LibManage/img/bookIcon.jpg);\n"
"}\n"
"")
        self.widgetIcon.setObjectName("widgetIcon")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 100, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font-weight: 900;\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font-weight: 900;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 240, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"font-weight: 900;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblpwd.setText(_translate("MainWindow", "password"))
        self.lbluser.setText(_translate("MainWindow", "username"))
        self.btnlogin.setText(_translate("MainWindow", "login"))
        self.pushButton.setText(_translate("MainWindow", "Sign up"))
        self.label.setText(_translate("MainWindow", "Library"))
        self.label_2.setText(_translate("MainWindow", "Management"))
        self.label_3.setText(_translate("MainWindow", "System"))
