# Form implementation generated from reading ui file 'Searchbooks.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: #F0FDF4;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtsearch = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtsearch.setGeometry(QtCore.QRect(160, 70, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.txtsearch.setFont(font)
        self.txtsearch.setObjectName("txtsearch")
        self.btnsearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnsearch.setGeometry(QtCore.QRect(650, 74, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        self.btnsearch.setFont(font)
        self.btnsearch.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: #22C55E;")
        self.btnsearch.setObjectName("btnsearch")
        self.tablebooks = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tablebooks.setGeometry(QtCore.QRect(150, 190, 601, 281))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tablebooks.setFont(font)
        self.tablebooks.setStyleSheet("QTableWidget {\n"
"    background-color: #F0FDF4;\n"
"    alternate-background-color: #DCFCE7;\n"
"    color: #14532D;\n"
"    gridline-color: #86EFAC;\n"
"    border: 1px solid #22C55E;\n"
"    selection-background-color: #16A34A;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #033315;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 6px;\n"
"    border: none;\n"
"}")
        self.tablebooks.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tablebooks.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.tablebooks.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tablebooks.setAutoScroll(True)
        self.tablebooks.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.tablebooks.setObjectName("tablebooks")
        self.tablebooks.setColumnCount(8)
        self.tablebooks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        item.setFont(font)
        self.tablebooks.setHorizontalHeaderItem(7, item)
        self.btnclear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnclear.setGeometry(QtCore.QRect(560, 500, 80, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.btnclear.setFont(font)
        self.btnclear.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: #22C55E;")
        self.btnclear.setObjectName("btnclear")
        self.btnback = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnback.setGeometry(QtCore.QRect(650, 500, 80, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.btnback.setFont(font)
        self.btnback.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: #22C55E;")
        self.btnback.setObjectName("btnback")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.radioTitle = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioTitle.setGeometry(QtCore.QRect(210, 40, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.radioTitle.setFont(font)
        self.radioTitle.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioTitle.setChecked(True)
        self.radioTitle.setObjectName("radioTitle")
        self.radioAuthor = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioAuthor.setGeometry(QtCore.QRect(320, 40, 90, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.radioAuthor.setFont(font)
        self.radioAuthor.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioAuthor.setObjectName("radioAuthor")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 141, 571))
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background-color: #15803D")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.widget_2.setStyleSheet("QWidget{\n"
"    border-image: url(D:/first/LibManage/img/bookIcon.jpg);\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(40, 0, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnadd = QtWidgets.QPushButton(parent=self.frame)
        self.btnadd.setGeometry(QtCore.QRect(-2, 100, 91, 41))
        self.btnadd.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #166534;\n"
"}")
        self.btnadd.setObjectName("btnadd")
        self.btnedit = QtWidgets.QPushButton(parent=self.frame)
        self.btnedit.setGeometry(QtCore.QRect(-1, 138, 91, 31))
        self.btnedit.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #166534;\n"
"}")
        self.btnedit.setObjectName("btnedit")
        self.btndelete = QtWidgets.QPushButton(parent=self.frame)
        self.btndelete.setGeometry(QtCore.QRect(-2, 166, 101, 41))
        self.btndelete.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #166534;\n"
"}")
        self.btndelete.setObjectName("btndelete")
        self.btnview = QtWidgets.QPushButton(parent=self.frame)
        self.btnview.setGeometry(QtCore.QRect(0, 197, 91, 41))
        self.btnview.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #166534;\n"
"}")
        self.btnview.setObjectName("btnview")
        self.btnothers = QtWidgets.QPushButton(parent=self.frame)
        self.btnothers.setGeometry(QtCore.QRect(0, 230, 101, 41))
        self.btnothers.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #166534;\n"
"}")
        self.btnothers.setObjectName("btnothers")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnsearch.setText(_translate("MainWindow", "Search"))
        item = self.tablebooks.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tablebooks.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tablebooks.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tablebooks.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tablebooks.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Publisher"))
        item = self.tablebooks.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tablebooks.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tablebooks.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Price"))
        self.btnclear.setText(_translate("MainWindow", "Clear"))
        self.btnback.setText(_translate("MainWindow", "Back"))
        self.label_2.setText(_translate("MainWindow", "Search by"))
        self.radioTitle.setText(_translate("MainWindow", "Title"))
        self.radioAuthor.setText(_translate("MainWindow", "Author"))
        self.label.setText(_translate("MainWindow", "LMS"))
        self.btnadd.setText(_translate("MainWindow", "Add Books"))
        self.btnedit.setText(_translate("MainWindow", "Edit Books"))
        self.btndelete.setText(_translate("MainWindow", "Delete Books"))
        self.btnview.setText(_translate("MainWindow", "View"))
        self.btnothers.setText(_translate("MainWindow", "others"))
