# Form implementation generated from reading ui file 'SignupDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QDialog {\n"
"     background-color: #F0FDF4;\n"
"}")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(130, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(18, 200, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 49, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 110, 49, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.txtname = QtWidgets.QLineEdit(parent=Dialog)
        self.txtname.setGeometry(QtCore.QRect(143, 80, 241, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(True)
        self.txtname.setFont(font)
        self.txtname.setAutoFillBackground(False)
        self.txtname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtname.setText("")
        self.txtname.setObjectName("txtname")
        self.txtnic = QtWidgets.QLineEdit(parent=Dialog)
        self.txtnic.setGeometry(QtCore.QRect(143, 110, 241, 24))
        self.txtnic.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtnic.setText("")
        self.txtnic.setObjectName("txtnic")
        self.txtuser = QtWidgets.QLineEdit(parent=Dialog)
        self.txtuser.setGeometry(QtCore.QRect(143, 140, 241, 24))
        self.txtuser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtuser.setText("")
        self.txtuser.setObjectName("txtuser")
        self.txtpwd = QtWidgets.QLineEdit(parent=Dialog)
        self.txtpwd.setGeometry(QtCore.QRect(143, 170, 241, 24))
        self.txtpwd.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtpwd.setText("")
        self.txtpwd.setObjectName("txtpwd")
        self.txtpwd2 = QtWidgets.QLineEdit(parent=Dialog)
        self.txtpwd2.setGeometry(QtCore.QRect(143, 200, 241, 24))
        self.txtpwd2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtpwd2.setText("")
        self.txtpwd2.setObjectName("txtpwd2")
        self.btnsave = QtWidgets.QPushButton(parent=Dialog)
        self.btnsave.setGeometry(QtCore.QRect(160, 240, 80, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.btnsave.setFont(font)
        self.btnsave.setStyleSheet("QPushButton{\n"
"    background-color: #22C55E;\n"
"    color:black;\n"
"}")
        self.btnsave.setObjectName("btnsave")
        self.btnclose = QtWidgets.QPushButton(parent=Dialog)
        self.btnclose.setGeometry(QtCore.QRect(280, 240, 80, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.btnclose.setFont(font)
        self.btnclose.setStyleSheet("QPushButton{\n"
"    background-color: #22C55E;\n"
"    color:black;\n"
"}")
        self.btnclose.setObjectName("btnclose")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "create account"))
        self.label_2.setText(_translate("Dialog", "User name"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.label_4.setText(_translate("Dialog", "Confirm password"))
        self.label_5.setText(_translate("Dialog", "Name"))
        self.label_6.setText(_translate("Dialog", "NIC"))
        self.btnsave.setText(_translate("Dialog", "Save"))
        self.btnclose.setText(_translate("Dialog", "Close"))
